### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by kvak** [bradfordboyle/pyglpk#11]
Hi,

Thanks for this project, looks great,

I'm not sure this is the right place to post this,  but I am trying to get to grip with this lib (I have prior experience of calling GLPK from R and cvxopt) and I think this could help people more generally.

I am looking for a brief (classical) example. Something like the example page 74 ('As a simple example we solve the LP') of https://media.readthedocs.org/pdf/cvxopt/latest/cvxopt.pdf. 

Would it be possible to write this simple case? It will help me get started. My idea is to bootstrap from that simple example and eventually commit a 'examples for dummies' file;)

Thanks!

**Comment by bradfordboyle** [comment]
Take a look at pyglpk/html/ex_ref.html. This is the original HTML documentation, but I would welcome a pull request that converts/updates the docs to use something like readthedocs.org for hosting.
