### ISSUE TITLE
pip install glpk: glpk-0.3.tar.gz ?

### ISSUE THREAD

**Issue by denis-bz** [bradfordboyle/pyglpk#30]
Bradford, could you please try `pip install glpk` ?
pip download --> glpk-0.3.tar.gz  all from 2013-04-16, LPXKKT undefined
pyglpk-master.zip from github is all 12-08-18 i.e. 2018
and `unzip; cd; pip install -e .` works.
(There must be a one-step `pip install git+https:...` that works, haven't found it)
Thanks, cheers

**Comment by bradfordboyle** [comment]
The [upload of pyglpk to PyPI](https://pypi.org/project/glpk/) was originally done by someone not affiliated with this fork. I've reached out to them to see if I can upload newer versions. In the meantime, the following should work:

```
pip install git+https://github.com/bradfordboyle/pyglpk
```

**Comment by bradfordboyle** [comment]
The newest version (v0.4.5) has been uploaded to PyPI and you should be able to run `pip install glpk==0.4.5` now.
