### ISSUE TITLE
ARM build?

### ISSUE THREAD

**Issue by ecosang** [bradfordboyle/pyglpk#40]
Hi thanks for maintaining the package.
pyglpk only available at x64 architecture.

Is there any plan to support ARM build for Apple silicon chipset?

**Comment by bradfordboyle** [comment]
I've tested pyglpk on both Linux arm64 and Apple Silicon and it should work. For macOS, you may need to set extra environment variables when installing. Assuming you have installed glpk with Homebrew (i.e., `brew install glpk`) and you are trying to install pyglpk with `pip`, the following should work for you:

```sh
export CFLAGS="$(brew --prefix)/include"
export LDFLAGS="$(brew --prefix/lib"
pip install glpk
```

**Comment by bradfordboyle** [comment]
There was a build issue on macOS but it was unrelated to x86_64 vs arm. A new release (v0.4.7) has been published to PyPI and I've verified that this works on Apple Silicon.
